/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembelian;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpupuk = new javax.swing.JButton();
        txtlogout = new javax.swing.JButton();
        txtpendaftarankt = new javax.swing.JButton();
        txtpenjualan1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bghome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpupuk.setBackground(new java.awt.Color(0, 255, 0));
        txtpupuk.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtpupuk.setForeground(new java.awt.Color(255, 255, 255));
        txtpupuk.setText("PUPUK");
        txtpupuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpupukActionPerformed(evt);
            }
        });
        getContentPane().add(txtpupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 200, 50));

        txtlogout.setBackground(new java.awt.Color(51, 255, 0));
        txtlogout.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtlogout.setForeground(new java.awt.Color(255, 255, 255));
        txtlogout.setText("LOGOUT");
        txtlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(txtlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, 164, 55));

        txtpendaftarankt.setBackground(new java.awt.Color(0, 255, 0));
        txtpendaftarankt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtpendaftarankt.setForeground(new java.awt.Color(255, 255, 255));
        txtpendaftarankt.setText("PENDAFTARAN KT");
        txtpendaftarankt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpendaftaranktActionPerformed(evt);
            }
        });
        getContentPane().add(txtpendaftarankt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 260, 50));

        txtpenjualan1.setBackground(new java.awt.Color(0, 255, 0));
        txtpenjualan1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtpenjualan1.setForeground(new java.awt.Color(255, 255, 255));
        txtpenjualan1.setText("PENJUALAN");
        txtpenjualan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpenjualan1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtpenjualan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembelian/Untitled-2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 250, 240));

        bghome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembelian/1.1.jpg"))); // NOI18N
        getContentPane().add(bghome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlogoutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Yakin nih mau keluar?", "Yakin", JOptionPane.YES_NO_OPTION)  == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_txtlogoutActionPerformed

    private void txtpenjualan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpenjualan1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        penjualan a = new penjualan();
        a.setVisible(true);
    }//GEN-LAST:event_txtpenjualan1ActionPerformed

    private void txtpendaftaranktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpendaftaranktActionPerformed
        // TODO add your handling code here:
        this.dispose();
        pendaftarankt a = new pendaftarankt();
        a.setVisible(true);
    }//GEN-LAST:event_txtpendaftaranktActionPerformed

    private void txtpupukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpupukActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jenispupuk a = new jenispupuk();
        a.setVisible(true);
    }//GEN-LAST:event_txtpupukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bghome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton txtlogout;
    private javax.swing.JButton txtpendaftarankt;
    private javax.swing.JButton txtpenjualan1;
    private javax.swing.JButton txtpupuk;
    // End of variables declaration//GEN-END:variables
}
