/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembelian;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtusername = new javax.swing.JTextField();
        txtregister = new javax.swing.JButton();
        txtlogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelusername = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelpassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        bglogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 340, 40));

        txtregister.setBackground(new java.awt.Color(0, 255, 0));
        txtregister.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtregister.setForeground(new java.awt.Color(255, 255, 255));
        txtregister.setText("REGISTER");
        txtregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregisterActionPerformed(evt);
            }
        });
        getContentPane().add(txtregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 170, 70));

        txtlogin.setBackground(new java.awt.Color(0, 255, 0));
        txtlogin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtlogin.setForeground(new java.awt.Color(255, 255, 255));
        txtlogin.setText("LOGIN");
        txtlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginActionPerformed(evt);
            }
        });
        getContentPane().add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 170, 70));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelusername.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelusername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelusername.setText("USERNAME");
        jPanel1.add(jLabelusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 130, 40));

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelpassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelpassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelpassword.setText("PASSWORD");
        jPanel2.add(jLabelpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 130, 40));

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 340, 40));

        bglogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembelian/1.0.jpg"))); // NOI18N
        getContentPane().add(bglogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 730));

        pack();
    }// </editor-fold>                        

    private void txtloginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            // TODO add your handling code here:
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM admin WHERE Username='" + txtusername.getText() +"' and Password='"+ txtpassword.getText() + "'";
            ResultSet rs = s.executeQuery(sql);
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Login Berhasil");
                this.dispose();
                home a = new home();
                a.setVisible(true);
                
            }else{
                JOptionPane.showMessageDialog(null, "Login Gagal"); 
                txtpassword.requestFocus();
        }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }                                        

    private void txtregisterActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        this.dispose();
        register a = new register();
        a.setVisible(true);
    }                                           

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel bglogin;
    private javax.swing.JLabel jLabelpassword;
    private javax.swing.JLabel jLabelusername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton txtlogin;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JButton txtregister;
    private javax.swing.JTextField txtusername;
    // End of variables declaration                   
}
