/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembelian;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class penjualan extends javax.swing.JFrame {

    /**
     * Creates new form penjualan
     */
    public penjualan() {
        initComponents();
        tampiltabel();
        autonumber();
        tampilcombo();
    }
public void tampilcombo(){
        try {
            String sql = "select * from pendaftarankartutani, jenispupuk, admin";
            Connection c = koneksi.getKoneksi();    
            PreparedStatement p = c.prepareStatement(sql);
            ResultSet rs = p.executeQuery();
            
            while(rs.next()){
                txtidpelanggan.addItem(rs.getString("Id_Pelanggan"));
                txtidpupuk.addItem(rs.getString("Id_Pupuk"));
                txtidadmin.addItem(rs.getString("Id_Admin"));
            }
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
        } catch (SQLException ex) {
            Logger.getLogger(penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public void tampiltabel(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("ID Order");
        tb.addColumn("Tanggal");
        tb.addColumn("ID Admin");
        tb.addColumn("ID Pelanggan");
        tb.addColumn("ID Pupuk");
        tb.addColumn("Jumlah Beli");
        tb.addColumn("Total");
        tb.addColumn("Bayar");
        tb.addColumn("Kembalian");
        txtdatapenjualan.setModel(tb);
        try{
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM penjualanpupuk";
            ResultSet rs = s.executeQuery(sql);
            
            while(rs.next()){
                tb.addRow(new Object[]{
                    rs.getString("Id_Order"), 
                    rs.getString("Tanggal_Order"),
                    rs.getString("Id_Pelanggan"),
                    rs.getString("Id_Admin"),
                    rs.getString("Id_Pupuk"),
                    rs.getString("Jumlah_Beli"),
                    rs.getString("Total_Harga"),
                    rs.getString("Jumlah_Bayar"),
                    rs.getString("Kembali"),
                        
                });
                
            }
            
        }catch(Exception e){
            System.out.println("tampil_tabel error");
        }
    }
    private void clear(){
        autonumber();
        txttglorder.setDate(null);
        txtjmlbeli.setText(null);
        txttotalhrg.setText(null);
        txtbayar.setText(null);
        txtkembalian.setText(null);
  }
  
       public void autonumber(){
        try{
        Connection c = koneksi.getKoneksi();
        Statement s = c.createStatement();
        String sql = "SELECT * FROM penjualanpupuk ORDER BY Id_Order DESC";
        ResultSet rs = s.executeQuery(sql); 
        
        if(rs.next()){
            String NoID = rs.getString("Id_Order").substring(2);
            String ID = "" + (Integer.parseInt(NoID)+1);
            String Zero = "";
            
            if (ID.length()==1)
            {Zero = "00";}
            else if (ID.length()==2)
            {Zero = "0";}
            else if (ID.length()==3)
            {Zero = "";}
            
            txtidorder.setText("OR" + Zero + ID);
        }else{
            txtidorder.setText("OR001");
        }
        rs.close();
        s.close();
    }catch(Exception e){
        System.out.println("autonumber error");
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtjmlbeli = new javax.swing.JTextField();
        txttotalhrg = new javax.swing.JTextField();
        txtidorder = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdatapenjualan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txtsimpan = new javax.swing.JButton();
        txtedit = new javax.swing.JButton();
        txthapus = new javax.swing.JButton();
        txtcetak = new javax.swing.JButton();
        txtkembali = new javax.swing.JButton();
        txtidpelanggan = new javax.swing.JComboBox<>();
        txtidpupuk = new javax.swing.JComboBox<>();
        txtidadmin = new javax.swing.JComboBox<>();
        txttglorder = new com.toedter.calendar.JDateChooser();
        bgpenjualan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtjmlbeli.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtjmlbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlbeliActionPerformed(evt);
            }
        });
        getContentPane().add(txtjmlbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 360, 30));

        txttotalhrg.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txttotalhrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalhrgActionPerformed(evt);
            }
        });
        getContentPane().add(txttotalhrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 360, 30));

        txtidorder.setEditable(false);
        txtidorder.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtidorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidorderActionPerformed(evt);
            }
        });
        getContentPane().add(txtidorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 360, 30));

        txtkembalian.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembalianActionPerformed(evt);
            }
        });
        getContentPane().add(txtkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 360, 30));

        txtbayar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        getContentPane().add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 360, 30));

        txtdatapenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Order", "Tanggal Order", "ID Pelanggan", "Id Admin", "Id Pupuk", "Jumlah Beli", "Total Harga", "Jumlah Bayar", "Kembali"
            }
        ));
        txtdatapenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdatapenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtdatapenjualan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 620, 350));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(102, 255, 102));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("KEMBALIAN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 140, 30));

        jPanel4.setBackground(new java.awt.Color(0, 153, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(102, 255, 102));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("BAYAR");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel5.setBackground(new java.awt.Color(0, 153, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(102, 255, 102));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("BAYAR");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 140, 30));

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(102, 255, 102));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("JUMLAH BELI");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(102, 255, 102));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("BAYAR");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        jPanel12.setBackground(new java.awt.Color(0, 153, 0));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(102, 255, 102));
        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("ID ADMIN");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel13.setBackground(new java.awt.Color(0, 153, 0));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(102, 255, 102));
        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("BAYAR");
        jPanel13.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 140, 30));

        jPanel6.setBackground(new java.awt.Color(0, 153, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(102, 255, 102));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("TOTAL");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel7.setBackground(new java.awt.Color(0, 153, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(102, 255, 102));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BAYAR");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 140, 30));

        jPanel8.setBackground(new java.awt.Color(0, 153, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(102, 255, 102));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ID PUPUK");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel9.setBackground(new java.awt.Color(0, 153, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(102, 255, 102));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("BAYAR");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, 30));

        jPanel10.setBackground(new java.awt.Color(0, 153, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 153, 0));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(102, 255, 102));
        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("BAYAR");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        jLabel19.setBackground(new java.awt.Color(102, 255, 102));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ID PELANGGAN");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 140, 30));

        jPanel14.setBackground(new java.awt.Color(0, 153, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(0, 153, 0));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(102, 255, 102));
        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("BAYAR");
        jPanel15.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        jPanel16.setBackground(new java.awt.Color(0, 153, 0));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(102, 255, 102));
        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("ID ADMIN");
        jPanel16.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel17.setBackground(new java.awt.Color(0, 153, 0));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(102, 255, 102));
        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("BAYAR");
        jPanel17.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 30));

        jLabel23.setBackground(new java.awt.Color(102, 255, 102));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("ID ADMIN");
        jPanel14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 30));

        jPanel18.setBackground(new java.awt.Color(0, 153, 0));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(102, 255, 102));
        jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("TANGGAL");
        jPanel18.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel19.setBackground(new java.awt.Color(0, 153, 0));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setBackground(new java.awt.Color(102, 255, 102));
        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("BAYAR");
        jPanel19.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        jPanel20.setBackground(new java.awt.Color(0, 153, 0));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBackground(new java.awt.Color(102, 255, 102));
        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("ID ADMIN");
        jPanel20.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel21.setBackground(new java.awt.Color(0, 153, 0));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setBackground(new java.awt.Color(102, 255, 102));
        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("BAYAR");
        jPanel21.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 30));

        getContentPane().add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 30));

        jPanel22.setBackground(new java.awt.Color(0, 153, 0));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(new java.awt.Color(102, 255, 102));
        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("ID ORDER");
        jPanel22.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel23.setBackground(new java.awt.Color(0, 153, 0));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setBackground(new java.awt.Color(102, 255, 102));
        jLabel32.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("BAYAR");
        jPanel23.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        jPanel24.setBackground(new java.awt.Color(0, 153, 0));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setBackground(new java.awt.Color(102, 255, 102));
        jLabel33.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("ID ADMIN");
        jPanel24.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel25.setBackground(new java.awt.Color(0, 153, 0));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(102, 255, 102));
        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("BAYAR");
        jPanel25.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        jPanel22.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 30));

        getContentPane().add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 140, 30));

        txtsimpan.setBackground(new java.awt.Color(0, 255, 0));
        txtsimpan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtsimpan.setForeground(new java.awt.Color(255, 255, 255));
        txtsimpan.setText("TAMBAH");
        txtsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(txtsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 130, 50));

        txtedit.setBackground(new java.awt.Color(0, 255, 0));
        txtedit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtedit.setForeground(new java.awt.Color(255, 255, 255));
        txtedit.setText("EDIT");
        txtedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteditActionPerformed(evt);
            }
        });
        getContentPane().add(txtedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 130, 50));

        txthapus.setBackground(new java.awt.Color(0, 255, 0));
        txthapus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txthapus.setForeground(new java.awt.Color(255, 255, 255));
        txthapus.setText("HAPUS");
        txthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthapusActionPerformed(evt);
            }
        });
        getContentPane().add(txthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 130, 50));

        txtcetak.setBackground(new java.awt.Color(0, 255, 0));
        txtcetak.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcetak.setForeground(new java.awt.Color(255, 255, 255));
        txtcetak.setText("CETAK");
        txtcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcetakActionPerformed(evt);
            }
        });
        getContentPane().add(txtcetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 130, 50));

        txtkembali.setBackground(new java.awt.Color(0, 255, 0));
        txtkembali.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtkembali.setForeground(new java.awt.Color(255, 255, 255));
        txtkembali.setText("KEMBALI");
        txtkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(txtkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 570, 130, 50));

        txtidpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpelangganActionPerformed(evt);
            }
        });
        getContentPane().add(txtidpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 360, 30));

        getContentPane().add(txtidpupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 360, 30));

        txtidadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidadminActionPerformed(evt);
            }
        });
        getContentPane().add(txtidadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 360, 30));

        txttglorder.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txttglorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 360, 30));

        bgpenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembelian/1.5.jpg"))); // NOI18N
        getContentPane().add(bgpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjmlbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlbeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlbeliActionPerformed

    private void txttotalhrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalhrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalhrgActionPerformed

    private void txtidorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidorderActionPerformed

    private void txtkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsimpanActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(txttglorder.getDate()));
        String Id_Order = txtidorder.getText();
        String Id_Admin = (String) txtidadmin.getSelectedItem();
        String Id_Pupuk = (String) txtidpupuk.getSelectedItem();
        String Id_Pelanggan = (String) txtidpelanggan.getSelectedItem();
        String Jumlah_Beli = txtjmlbeli.getText();
        String Total = txttotalhrg.getText();
        String Bayar = txtbayar.getText();
        String Kembali = txtkembalian.getText();

        if (Id_Order.equals("") || tanggal.equals("") || Id_Admin.equals("") || Id_Pupuk.equals("") || Jumlah_Beli.equals("") || Total.equals("") || Bayar.equals("") || Kembali.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Data Dengan Lengkap!");
        }else{
            try{
                Connection c = koneksi.getKoneksi();
                String sql = "INSERT INTO penjualanpupuk VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, Id_Order);
                p.setString(2, tanggal);
                p.setString(3, Id_Pelanggan);
                p.setString(4, Id_Admin);
                p.setString(5, Id_Pupuk);
                p.setString(6, Jumlah_Beli);
                p.setString(7, Total);
                p.setString(8, Bayar);
                p.setString(9, Kembali);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "Data Ditambahkan");
            } catch (SQLException ex) {
                System.out.println("Error");
            }
            clear();
            tampiltabel();
            tampilcombo();
        }
    }//GEN-LAST:event_txtsimpanActionPerformed

    private void txteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteditActionPerformed
        // TODO add your handling code here: try {
            String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(txttglorder.getDate()));
            try{
                Connection c = koneksi.getKoneksi();
                Statement s = c.createStatement();
                String SQL ="update penjualanpupuk SET Id_Order = '"+txtidorder.getText()+"', "
                + "Tanggal_Order = '"+tanggal+"', "
                + "Id_Pelanggan = '"+txtidpelanggan.getSelectedItem()+"', "
                + "Id_Admin = '"+txtidadmin.getSelectedItem()+"', "
                + "Id_pupuk = '"+txtidpupuk.getSelectedItem()+"', "
                + "Jumlah_Beli = '"+txtjmlbeli.getText()+"', "
                + "Total_Harga = '"+txttotalhrg.getText()+"'," 
                + "Jumlah_Bayar = '"+txtbayar.getText()+"', " 
                + "Kembali = '"+txtkembalian.getText()+"' WHERE Id_Order = '"+txtidorder.getText()+"'";
                s.executeUpdate(SQL);
                tampiltabel();
                s.close();
                clear();
                JOptionPane.showMessageDialog(null, "berhasil edit");

            }catch(Exception exc){
                System.err.println(exc.getMessage());

    }//GEN-LAST:event_txteditActionPerformed
    }
    private void txthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthapusActionPerformed
        // TODO add your handling code here:
        String hapus =
        txtdatapenjualan.getValueAt(txtdatapenjualan.getSelectedRow(),0).toString();
        try {
            Connection c = koneksi.getKoneksi();
            PreparedStatement pStatement = null;
            String sql ="DELETE FROM penjualanpupuk WHERE Id_Order=? ";
            pStatement = c.prepareStatement(sql);
            pStatement.setString(1, hapus);
            int intTambah= pStatement.executeUpdate();
            if (intTambah>0)
            JOptionPane.showMessageDialog(this,
                "Hapus data sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Hapus data gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            pStatement.close();
            tampiltabel();
            clear();
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
    }//GEN-LAST:event_txthapusActionPerformed
    }
    private void txtcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcetakActionPerformed
        // TODO add your handling code here:
        com.mysql.jdbc.Connection conn = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(penjualan.class.getName()) .log(Level.SEVERE, null, ex);
        }
        try {
            conn = (com.mysql.jdbc.Connection) DriverManager. getConnection("jdbc:mysql://localhost:3306/pembelianpupuk", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }

        String file = "D:\\Document\\KULIAH\\TUGAS\\CODING\\sangtani2\\src\\pembelian\\datapenjualan.jrxml";
        JasperReport jr;
        try {
            jr = JasperCompileManager.compileReport(file);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, conn);
            JasperViewer.viewReport(jp);

        }catch (JRException ex) {
            Logger.getLogger(pendaftarankt.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtcetakActionPerformed

    private void txtkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        home a = new home();
        a.setVisible(true);
    }//GEN-LAST:event_txtkembaliActionPerformed

    private void txtdatapenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdatapenjualanMouseClicked
        // TODO add your handling code here:
        try {
            Connection c = koneksi.getKoneksi();
            int row =txtdatapenjualan.getSelectedRow();
            String tabel_klik=(txtdatapenjualan.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = c.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from penjualanpupuk where Id_Order= '"+tabel_klik+"'");
            if(sql.next()){
                String id_order = sql.getString("Id_Order");
                txtidorder.setText(id_order);
                Date tgl_order = sql.getDate("Tanggal_Order");
                txttglorder.setDate(tgl_order);
                String id_admin = sql.getString("Id_Admin");
                txtidadmin.setSelectedItem(id_admin);
                String id_pelanggan = sql.getString("Id_Pelanggan");
                txtidpelanggan.setSelectedItem(id_pelanggan);
                String id_pupuk = sql.getString("Id_Pupuk");
                txtidpupuk.setSelectedItem(id_pupuk);
                String jml_beli = sql.getString("Jumlah_Beli");
                txtjmlbeli.setText(jml_beli);
                String total_hrg = sql.getString("Total_Harga");
                txttotalhrg.setText(total_hrg);
                String bayar = sql.getString("Jumlah_Bayar");
                txtbayar.setText(bayar);
                String kembalian = sql.getString("Kembali");
                txtkembalian.setText(kembalian);
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_txtdatapenjualanMouseClicked

    private void txtidpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpelangganActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtidpelangganActionPerformed

    private void txtidadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgpenjualan;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JButton txtcetak;
    private javax.swing.JTable txtdatapenjualan;
    private javax.swing.JButton txtedit;
    private javax.swing.JButton txthapus;
    private javax.swing.JComboBox<String> txtidadmin;
    private javax.swing.JTextField txtidorder;
    private javax.swing.JComboBox<String> txtidpelanggan;
    private javax.swing.JComboBox<String> txtidpupuk;
    private javax.swing.JTextField txtjmlbeli;
    private javax.swing.JButton txtkembali;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JButton txtsimpan;
    private com.toedter.calendar.JDateChooser txttglorder;
    private javax.swing.JTextField txttotalhrg;
    // End of variables declaration//GEN-END:variables
}
