/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembelian;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        txtadmin.setEnabled(false);
        autonumber();
        validasiusername.setVisible(false);
        validasipassword1.setVisible(false);
        
    }
    public void autonumber() {
    try{
        Connection c = koneksi.getKoneksi();
        Statement s = c.createStatement();
        String sql = "SELECT * FROM admin ORDER BY Id_Admin DESC";
        ResultSet rs = s.executeQuery(sql); 
        
        if(rs.next()){
            String NoID = rs.getString("Id_Admin").substring(2);
            String ID = "" + (Integer.parseInt(NoID)+1);
            String Zero = "";
            
            if (ID.length()==1)
            {Zero = "00";}
            else if (ID.length()==2)
            {Zero = "0";}
            else if (ID.length()==3)
            {Zero = "";}
            
            txtadmin.setText("AD" + Zero + ID);
        }else{
            txtadmin.setText("AD001");
        }
        rs.close();
        s.close();
    }catch(Exception e){
        System.out.println("autonumber error");
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtusernamereg = new javax.swing.JTextField();
        txtadmin = new javax.swing.JTextField();
        txtregister = new javax.swing.JButton();
        txtbatal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtpasswordreg = new javax.swing.JPasswordField();
        validasiusername = new javax.swing.JLabel();
        validasipassword1 = new javax.swing.JLabel();
        inipanelcok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusernamereg.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtusernamereg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameregActionPerformed(evt);
            }
        });
        getContentPane().add(txtusernamereg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 490, 40));

        txtadmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 490, 40));

        txtregister.setBackground(new java.awt.Color(0, 255, 0));
        txtregister.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtregister.setForeground(new java.awt.Color(255, 255, 255));
        txtregister.setText("REGISTER");
        txtregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregisterActionPerformed(evt);
            }
        });
        getContentPane().add(txtregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 220, 70));

        txtbatal.setBackground(new java.awt.Color(0, 255, 0));
        txtbatal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtbatal.setForeground(new java.awt.Color(255, 255, 255));
        txtbatal.setText("BATAL");
        txtbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbatalActionPerformed(evt);
            }
        });
        getContentPane().add(txtbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 220, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembelian/Untitled-1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 460, 400));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(102, 255, 102));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 140, 40));

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USERNAME");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 140, 40));

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID ADMIN");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, 40));

        txtpasswordreg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpasswordreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordregActionPerformed(evt);
            }
        });
        getContentPane().add(txtpasswordreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 490, 40));

        validasiusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        validasiusername.setForeground(new java.awt.Color(255, 0, 0));
        validasiusername.setText("pesan validasi");
        getContentPane().add(validasiusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 340, 20));

        validasipassword1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        validasipassword1.setForeground(new java.awt.Color(255, 0, 0));
        validasipassword1.setText("pesan validasi");
        getContentPane().add(validasipassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 340, 20));

        inipanelcok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembelian/1.3.jpg"))); // NOI18N
        getContentPane().add(inipanelcok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>                        

    private void txtregisterActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        String Id_Admin = txtadmin.getText();
        String Username = txtusernamereg.getText().trim();
        String Password = txtpasswordreg.getText();
                     
        if (Password.equals("") || Username.equals("")){
            JOptionPane.showMessageDialog(null, "Username dan Password tidak boleh kosong");
        }else if (Username.length() < 5){
            validasiusername.setText("Username minimal 5 karakter");
            validasiusername.setVisible(true);          
            validasipassword1.setVisible(false);
        }else if (Password.length() > 12){          
            validasipassword1.setText("Password maksimal 12 karakter");         
            validasipassword1.setVisible(true);
            validasiusername.setVisible(false);
        }else if (Password.length() < 5 ){          
            validasipassword1.setText("Password minimal 5 karakter");         
            validasipassword1.setVisible(true);
            validasiusername.setVisible(false);    
        }else{
            try{
                Connection c = koneksi.getKoneksi();
                String sql = "INSERT INTO admin VALUES (?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, Id_Admin);
                p.setString(2, Username);
                p.setString(3, Password);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "Akun berhasil dibuat");
            } catch (SQLException ex) {
                System.out.println("Error");
            }finally{
               this.dispose();
               login a = new login();
               a.setVisible(true);
            }
        }
    }                                           

    private void txtbatalActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.dispose();
        login a = new login();
        a.setVisible(true);
    }                                        

    private void txtpasswordregActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txtusernameregActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel inipanelcok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtadmin;
    private javax.swing.JButton txtbatal;
    private javax.swing.JPasswordField txtpasswordreg;
    private javax.swing.JButton txtregister;
    private javax.swing.JTextField txtusernamereg;
    private javax.swing.JLabel validasipassword1;
    private javax.swing.JLabel validasiusername;
    // End of variables declaration                   
}
